import { Category, EffectItem, RequiredPlugin } from './types';

export const CATEGORIES: Category[] = [
  {
    id: 'renk-efektleri',
    name: 'Renk Efektleri',
    titleTr: 'Renk Efektleri',
    iconName: 'Sparkles',
    countText: '10 RENK EFEKTİ',
    count: 10,
    badgeColor: 'bg-violet-500/10 text-violet-400 border border-violet-500/20',
    glowColor: 'shadow-[0_0_20px_rgba(139,92,246,0.12)] border-violet-500/30',
    accentColor: 'text-violet-400',
  },
  {
    id: 'shakeler',
    name: "Shake'ler",
    titleTr: "Shake'ler",
    iconName: 'Zap',
    countText: '5 SHAKE EFEKTİ',
    count: 5,
    badgeColor: 'bg-amber-500/10 text-amber-400 border border-amber-500/20',
    glowColor: 'shadow-[0_0_20px_rgba(245,158,11,0.12)] border-amber-500/30',
    accentColor: 'text-amber-400',
  },
  {
    id: 'twixtor-ayarlari',
    name: 'Twixtor Ayarları',
    titleTr: 'Twixtor Ayarları',
    iconName: 'Activity',
    countText: '2 TWIXTOR EFEKTİ',
    count: 2,
    badgeColor: 'bg-teal-500/10 text-teal-400 border border-teal-500/20',
    glowColor: 'shadow-[0_0_20px_rgba(20,184,166,0.12)] border-teal-500/30',
    accentColor: 'text-teal-400',
  },
  {
    id: 'gecis-efektleri',
    name: 'Geçiş Efektleri',
    titleTr: 'Geçiş Efektleri',
    iconName: 'MoveRight',
    countText: '7 GEÇİŞ EFEKTİ',
    count: 7,
    badgeColor: 'bg-cyan-500/10 text-cyan-400 border border-cyan-500/20',
    glowColor: 'shadow-[0_0_20px_rgba(6,182,212,0.12)] border-cyan-500/30',
    accentColor: 'text-cyan-400',
  },
  {
    id: 'diger-efektler',
    name: 'Diğer Efektler',
    titleTr: 'Diğer Efektler',
    iconName: 'Compass',
    countText: '5 ÖZEL EFEKT',
    count: 5,
    badgeColor: 'bg-pink-500/10 text-pink-400 border border-pink-500/20',
    glowColor: 'shadow-[0_0_20px_rgba(236,72,153,0.12)] border-pink-500/30',
    accentColor: 'text-pink-400',
  },
  {
    id: 'ses-efektleri',
    name: 'Ses Efektleri',
    titleTr: 'Ses Efektleri',
    iconName: 'Volume2',
    countText: '24 SES EFEKTİ',
    count: 24,
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/20',
    glowColor: 'shadow-[0_0_20px_rgba(16,185,129,0.12)] border-emerald-500/30',
    accentColor: 'text-emerald-400',
  },
];

export const REQUIRED_PLUGINS: RequiredPlugin[] = [
  {
    name: 'Sapphire (S_)',
    category: 'Sallantı, Parlama ve Geçişler',
    description: 'After Effects video editörlerinin olmazsa olmazı ana efekt paketidir. S_Shake, S_Glow, S_Distort vb. yüzlerce gelişmiş efekt içerir.',
    requirements: 'After Effects CC 2018 ve üzeri',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ', // Placeholder, custom embedding
    downloadUrl: '#',
  },
  {
    name: 'Boris FX Continuum (BCC)',
    category: 'Görsel Efektler ve Geçişler',
    description: 'BCC Fast Lens Blur, BCC Chroma Bands ve 3D parçacık efektleri için kullanılır. Özellikle anime ve oyun editlerinde sıkça tercih edilir.',
    requirements: 'After Effects CC 2020 ve üzeri',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    downloadUrl: '#',
  },
  {
    name: 'Magic Bullet Looks (Red Giant)',
    category: 'Renk Derecelendirme (CC)',
    description: 'Renk efektlerimizin (CC) büyük bir çoğunluğu bu plugini gerektirir. Sinematik ve doygun renk ayarları için profesyonel araçlar sunar.',
    requirements: 'After Effects CC 2019 ve üzeri',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    downloadUrl: '#',
  },
  {
    name: 'Twixtor / Twixtor Pro',
    category: 'Yavaş Çekim (Slow-motion)',
    description: 'Videolarınızı kare atlamadan, yapay zeka desteğiyle pürüzsüzce yavaşlatmanızı sağlar. Anime ve spor editleri için kritik öneme sahiptir.',
    requirements: 'After Effects CC 2015 ve üzeri',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    downloadUrl: '#',
  },
  {
    name: 'Deep Glow',
    category: 'Gerçekçi Parlama Efekti',
    description: 'After Effects\'in varsayılan glow efektinden kat kat daha gerçekçi, fiziksel tabanlı bir ışık parlaması üretir.',
    requirements: 'After Effects CC 2017 ve üzeri',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    downloadUrl: '#',
  },
  {
    name: 'RSMB (ReelSmart Motion Blur)',
    category: 'Hareket Bulanıklığı',
    description: 'Hızlı hareket eden nesnelere otomatik olarak gerçekçi kamera hareket bulanıklığı ekler, geçişlerin ve shake\'lerin daha akıcı görünmesini sağlar.',
    requirements: 'After Effects CC 2018 ve üzeri',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    downloadUrl: '#',
  },
];

export const EFFECT_ITEMS: EffectItem[] = [
  // --- RENK EFEKTLERİ (10) ---
  {
    id: 'cc-aesthetic',
    name: 'Aesthetic Dreamy CC',
    description: 'Videolarınıza rüya gibi yumuşak bir hava, parıltı ve pastel tonlar katar. Özellikle anime ve lo-fi editlerinde harika sonuç verir.',
    downloadUrl: 'https://parsmazi.com/packs/cc-aesthetic.ffx',
    fileSize: '42 KB',
    fileType: '.ffx',
    author: 'Pars Mazi',
    categoryId: 'renk-efektleri',
    views: 312,
    downloads: 145,
    requirements: ['Magic Bullet Looks', 'Deep Glow'],
    parameters: [
      { key: 'Saturate', value: '115%' },
      { key: 'Contrast', value: '60%' },
      { key: 'Glow Strength', value: '0.35' },
      { key: 'Warmth', value: '+12' },
    ]
  },
  {
    id: 'cc-cyber-neon',
    name: 'Cyberpunk Neon CC',
    description: 'Mavileri turkuaza, kırmızıları canlı fuşya tonlarına dönüştüren, yüksek kontrastlı fütüristik bir gece/sokak tarzı renk ayarıdır.',
    downloadUrl: 'https://parsmazi.com/packs/cc-cyber-neon.ffx',
    fileSize: '38 KB',
    fileType: '.ffx',
    author: 'Pars Mazi',
    categoryId: 'renk-efektleri',
    views: 289,
    downloads: 120,
    requirements: ['Magic Bullet Looks', 'Misfire'],
    parameters: [
      { key: 'Cyan Hue', value: 'Offset -15°' },
      { key: 'Magenta Lift', value: '12%' },
      { key: 'Saturate', value: '140%' },
    ]
  },
  {
    id: 'cc-vintage-film',
    name: 'Vintage Film 16mm CC',
    description: 'Gerçek nostaljik film greni, hafif sepyamsı gölgeler ve sıcak tonlarla klasik bir sinematik 16mm film havası oluşturur.',
    downloadUrl: 'https://parsmazi.com/packs/cc-vintage-film.ffx',
    fileSize: '45 KB',
    fileType: '.ffx',
    author: 'Pars Mazi',
    categoryId: 'renk-efektleri',
    views: 405,
    downloads: 210,
    requirements: ['Magic Bullet Looks', 'Dehancer / Sapphire Film'],
    parameters: [
      { key: 'Grain Amount', value: '25%' },
      { key: 'Vignette', value: '15%' },
      { key: 'Color Temperature', value: '5800K' },
    ]
  },
  {
    id: 'cc-dark-knight',
    name: 'Dark Knight Cinematic CC',
    description: 'Yeşil/mavi gölgeler, derin siyahlar ve düşük doygunluk ile dramatik, gizemli ve soğuk bir sinematik atmosfer yaratır.',
    downloadUrl: 'https://parsmazi.com/packs/cc-dark-knight.ffx',
    fileSize: '35 KB',
    fileType: '.ffx',
    author: 'Pars Mazi',
    categoryId: 'renk-efektleri',
    views: 198,
    downloads: 88,
    requirements: ['Magic Bullet Looks'],
    parameters: [
      { key: 'Shadow Tint', value: '#1a2a2a' },
      { key: 'Highlight Gain', value: '95%' },
      { key: 'Saturation', value: '85%' },
    ]
  },
  {
    id: 'cc-anime-vibrant',
    name: 'Anime Vibrant Pop CC',
    description: 'Renkli çizimleri ve animasyonları patlatmak için geliştirilmiş, göz alıcı doygunluk ve temiz beyaz dengesi sunan preset.',
    downloadUrl: 'https://parsmazi.com/packs/cc-anime-vibrant.ffx',
    fileSize: '32 KB',
    fileType: '.ffx',
    author: 'Pars Mazi',
    categoryId: 'renk-efektleri',
    views: 560,
    downloads: 312,
    requirements: ['Magic Bullet Looks'],
    parameters: [
      { key: 'Contrast', value: '55%' },
      { key: 'Vibrance', value: '45%' },
      { key: 'Black Level', value: '-3%' },
    ]
  },
  {
    id: 'cc-pastel-soft',
    name: 'Pastel Soft Glow CC',
    description: 'Gözü yormayan yumuşak tonlar, artırılmış parlaklık ve ferahlatıcı pastel renk ağırlığı. Günlük editler için mükemmel.',
    downloadUrl: 'https://parsmazi.com/packs/cc-pastel-soft.ffx',
    fileSize: '29 KB',
    fileType: '.ffx',
    author: 'Pars Mazi',
    categoryId: 'renk-efektleri',
    views: 245,
    downloads: 115,
    requirements: ['Magic Bullet Looks', 'Deep Glow'],
    parameters: [
      { key: 'Exposure', value: '+0.4' },
      { key: 'Glow Threshold', value: '80%' },
      { key: 'Saturation', value: '105%' },
    ]
  },
  {
    id: 'cc-cold-winter',
    name: 'Cold Winter Bleak CC',
    description: 'Mavimsi soğuk tonları öne çıkaran, sıcak renkleri söndüren, melankolik ve karamsar editler için tasarlanmış CC.',
    downloadUrl: 'https://parsmazi.com/packs/cc-cold-winter.ffx',
    fileSize: '31 KB',
    fileType: '.ffx',
    author: 'Pars Mazi',
    categoryId: 'renk-efektleri',
    views: 187,
    downloads: 74,
    requirements: ['Magic Bullet Looks'],
    parameters: [
      { key: 'Temp', value: '-18' },
      { key: 'Green Tint', value: '+4' },
      { key: 'Contrast', value: '65%' },
    ]
  },
  {
    id: 'cc-autumn-cozy',
    name: 'Autumn Warm Cozy CC',
    description: 'Kahverengi, turuncu ve altın sarısı tonları ön plana çıkaran, hüzünlü sonbahar hissi uyandıran sıcak bir renk tonlaması.',
    downloadUrl: 'https://parsmazi.com/packs/cc-autumn-cozy.ffx',
    fileSize: '41 KB',
    fileType: '.ffx',
    author: 'Pars Mazi',
    categoryId: 'renk-efektleri',
    views: 220,
    downloads: 99,
    requirements: ['Magic Bullet Looks'],
    parameters: [
      { key: 'Orange Boost', value: '+20%' },
      { key: 'Warm Hue Lift', value: '10%' },
    ]
  },
  {
    id: 'cc-hdr-sharp',
    name: 'Ultra HDR Sharp CC',
    description: 'Video detaylarını inanılmaz derecede keskinleştiren ve gölgelerdeki saklı pikselleri gün yüzüne çıkaran HDR görünümü.',
    downloadUrl: 'https://parsmazi.com/packs/cc-hdr-sharp.ffx',
    fileSize: '36 KB',
    fileType: '.ffx',
    author: 'Pars Mazi',
    categoryId: 'renk-efektleri',
    views: 480,
    downloads: 260,
    requirements: ['Magic Bullet Looks', 'Sapphire Sharpen'],
    parameters: [
      { key: 'Sharpen Amount', value: '1.2' },
      { key: 'Shadow Recovery', value: '35%' },
      { key: 'Clarity', value: '40%' },
    ]
  },
  {
    id: 'cc-retro-synth',
    name: '80s Retro Synthwave CC',
    description: 'VHS kaset filtreleri ve 80\'ler synthwave neon moru/pembe tonlarının mükemmel birleşimi. Retro editler için idealdir.',
    downloadUrl: 'https://parsmazi.com/packs/cc-retro-synth.ffx',
    fileSize: '44 KB',
    fileType: '.ffx',
    author: 'Pars Mazi',
    categoryId: 'renk-efektleri',
    views: 310,
    downloads: 155,
    requirements: ['Magic Bullet Looks', 'BCC Damaged TV'],
    parameters: [
      { key: 'Mor Dengeleme', value: 'Aşırı (%30)' },
      { key: 'Chromatic Aberration', value: '0.15' },
    ]
  },

  // --- SHAKE'LER (5) ---
  {
    id: 'shake-y-smooth',
    name: 'Smooth Y-Shake (Dikey Sallantı)',
    description: 'Vuruş anlarında dikey (aşağı-yukarı) eksende mükemmel sönümlenen, en çok tercih edilen akıcı dikey sallantı efekti.',
    downloadUrl: 'https://parsmazi.com/packs/shake-y-smooth.ffx',
    fileSize: '15 KB',
    fileType: '.ffx',
    author: 'Pars Mazi',
    categoryId: 'shakeler',
    views: 740,
    downloads: 450,
    requirements: ['Sapphire (S_Shake)'],
    parameters: [
      { key: 'Amplitude', value: '1.8' },
      { key: 'Frequency', value: '8.0' },
      { key: 'Y Rand', value: '1.0' },
      { key: 'X Rand', value: '0.0' },
    ]
  },
  {
    id: 'shake-x-intense',
    name: 'Intense X-Shake (Yatay Sallantı)',
    description: 'Aksiyon, vuruş veya patlama sahnelerinde yatay sarsıntıyla sarsıcı bir etki yaratan yüksek enerjili yatay shake.',
    downloadUrl: 'https://parsmazi.com/packs/shake-x-intense.ffx',
    fileSize: '14 KB',
    fileType: '.ffx',
    author: 'Pars Mazi',
    categoryId: 'shakeler',
    views: 520,
    downloads: 290,
    requirements: ['Sapphire (S_Shake)'],
    parameters: [
      { key: 'Amplitude', value: '2.5' },
      { key: 'Frequency', value: '12.0' },
      { key: 'X Rand', value: '1.0' },
      { key: 'Y Rand', value: '0.1' },
    ]
  },
  {
    id: 'shake-rotational',
    name: 'Rotational 3D Shake',
    description: 'Kamerayı Z ekseninde (döndürerek) sallayan, genellikle ağır kurgularda veya 3D geçiş hissi yaratmak için kullanılan estetik sallantı.',
    downloadUrl: 'https://parsmazi.com/packs/shake-rotational.ffx',
    fileSize: '18 KB',
    fileType: '.ffx',
    author: 'Pars Mazi',
    categoryId: 'shakeler',
    views: 430,
    downloads: 220,
    requirements: ['Sapphire (S_Shake)'],
    parameters: [
      { key: 'Tilt Amplitude', value: '4.5°' },
      { key: 'Frequency', value: '6.5' },
      { key: 'Z-Distance Blur', value: 'Açık' },
    ]
  },
  {
    id: 'shake-cinematic-slow',
    name: 'Cinematic Slow Handheld Shake',
    description: 'Elde tutulan kamera hissi uyandıran, sürekli ve yumuşak, sinematik sahnelerde derinlik katan yavaş salınımlı shake.',
    downloadUrl: 'https://parsmazi.com/packs/shake-cinematic-slow.ffx',
    fileSize: '12 KB',
    fileType: '.ffx',
    author: 'Pars Mazi',
    categoryId: 'shakeler',
    views: 312,
    downloads: 145,
    requirements: ['After Effects Built-In (Wiggler)'],
    parameters: [
      { key: 'Frequency', value: '1.5 hz' },
      { key: 'Magnitude', value: '15px' },
    ]
  },
  {
    id: 'shake-glitch-jolt',
    name: 'Glitch Jolt Shake',
    description: 'Sallantı sırasında dijital bozulma (glitch) efekti tetikleyen, anlık zıplamalar yapan cyberpunk/tech edit tarzı shake.',
    downloadUrl: 'https://parsmazi.com/packs/shake-glitch-jolt.ffx',
    fileSize: '19 KB',
    fileType: '.ffx',
    author: 'Pars Mazi',
    categoryId: 'shakeler',
    views: 388,
    downloads: 195,
    requirements: ['Sapphire (S_Shake / S_Glitch)'],
    parameters: [
      { key: 'Amplitude', value: '3.0' },
      { key: 'Glitch Interval', value: '0.2s' },
    ]
  },

  // --- TWIXTOR AYARLARI (2) ---
  {
    id: 'twixtor-ultra-smooth',
    name: 'Twixtor 60fps Ultra Smooth Preset',
    description: 'Standart 24/30fps videoları yapay zeka ara kare ekleme teknolojisiyle 60 fps akıcılığına getiren pürüzsüz ağır çekim ayarı.',
    downloadUrl: 'https://parsmazi.com/packs/twixtor-ultra-smooth.ffx',
    fileSize: '10 KB',
    fileType: '.ffx',
    author: 'Pars Mazi',
    categoryId: 'twixtor-ayarlari',
    views: 890,
    downloads: 540,
    requirements: ['Twixtor Pro'],
    parameters: [
      { key: 'Display', value: 'Twixtorled' },
      { key: 'Input Fields', value: 'None' },
      { key: 'Motion Vectors', value: 'Best' },
      { key: 'Image Prep', value: 'Contrast/Edge Enhance' },
    ]
  },
  {
    id: 'twixtor-velocity',
    name: 'Twixtor Velocity Curve Builder',
    description: 'Hız eğrisi (Speed Ramp) kurgularınızda kırılma ve titremeleri engelleyen, yumuşacık hızlanma-yavaşlama geçişleri için ideal ayar.',
    downloadUrl: 'https://parsmazi.com/packs/twixtor-velocity.ffx',
    fileSize: '11 KB',
    fileType: '.ffx',
    author: 'Pars Mazi',
    categoryId: 'twixtor-ayarlari',
    views: 650,
    downloads: 380,
    requirements: ['Twixtor Pro', 'RSMB'],
    parameters: [
      { key: 'Frame Interp', value: 'Motion Weighted' },
      { key: 'Warping', value: 'Inverse' },
    ]
  },

  // --- GEÇİŞ EFEKTLERİ (7) ---
  {
    id: 'trans-zoom-in',
    name: 'Seamless Zoom In Transition',
    description: 'Sahneyi öne doğru derinlemesine çekerek bir sonraki klibe akıcı bir şekilde bağlayan pürüzsüz zoom-in geçiş efekti.',
    downloadUrl: 'https://parsmazi.com/packs/trans-zoom-in.ffx',
    fileSize: '25 KB',
    fileType: '.ffx',
    author: 'Pars Mazi',
    categoryId: 'gecis-efektleri',
    views: 670,
    downloads: 410,
    requirements: ['After Effects Motion Tile', 'Sapphire Distort'],
    parameters: [
      { key: 'Scale Start', value: '100%' },
      { key: 'Scale Peak', value: '300%' },
      { key: 'Motion Blur', value: 'On (RSMB)' },
    ]
  },
  {
    id: 'trans-slide-left',
    name: 'Whip Slide Left Transition',
    description: 'Sahneyi sol tarafa doğru kırbaç hızıyla kaydırarak geçen, hareket bulanıklığı yüksek dinamik bir geçiş.',
    downloadUrl: 'https://parsmazi.com/packs/trans-slide-left.ffx',
    fileSize: '21 KB',
    fileType: '.ffx',
    author: 'Pars Mazi',
    categoryId: 'gecis-efektleri',
    views: 480,
    downloads: 260,
    requirements: ['After Effects Built-In (Offset / CC Radial Blur)'],
    parameters: [
      { key: 'X-Offset Shift', value: '1920px' },
      { key: 'Blur Strength', value: '45' },
    ]
  },
  {
    id: 'trans-spin-twist',
    name: 'Spin Twist 3D Transition',
    description: 'Ekranı 180 derece kendi etrafında kıvırıp döndürerek diğer sahneye geçiş yaptıran popüler 3D kurgu geçişi.',
    downloadUrl: 'https://parsmazi.com/packs/trans-spin-twist.ffx',
    fileSize: '28 KB',
    fileType: '.ffx',
    author: 'Pars Mazi',
    categoryId: 'gecis-efektleri',
    views: 520,
    downloads: 305,
    requirements: ['Sapphire (S_BlurChannels)', 'Motion Tile'],
    parameters: [
      { key: 'Angle Rotation', value: '180°' },
      { key: 'Edge Mode', value: 'Mirror' },
    ]
  },
  {
    id: 'trans-glitch-flash',
    name: 'RGB Glitch Flash Transition',
    description: 'Sahneler arasında RGB renk kayması ve parlak beyaz patlaması (flash) yapan, müzik vuruşlarına çok yakışan geçiş.',
    downloadUrl: 'https://parsmazi.com/packs/trans-glitch-flash.ffx',
    fileSize: '32 KB',
    fileType: '.ffx',
    author: 'Pars Mazi',
    categoryId: 'gecis-efektleri',
    views: 450,
    downloads: 230,
    requirements: ['Sapphire (S_Glitch / S_Glow)'],
    parameters: [
      { key: 'Glow Width', value: '120' },
      { key: 'RGB Separation', value: '15px' },
    ]
  },
  {
    id: 'trans-lens-warp',
    name: 'Cinematic Lens Warp Transition',
    description: 'Mercek bozulması (fisheye lens) efektiyle ekranı bükerek yumuşak bir şekilde sahne değiştirmeyi sağlayan sinematik geçiş.',
    downloadUrl: 'https://parsmazi.com/packs/trans-lens-warp.ffx',
    fileSize: '27 KB',
    fileType: '.ffx',
    author: 'Pars Mazi',
    categoryId: 'gecis-efektleri',
    views: 390,
    downloads: 180,
    requirements: ['Sapphire (S_LensWarp)'],
    parameters: [
      { key: 'Warp Amount', value: '-0.4' },
      { key: 'Blur Radius', value: '25' },
    ]
  },
  {
    id: 'trans-blur-dissolve',
    name: 'Smooth Fast Blur Dissolve',
    description: 'Klipleri hızlıca bulanıklaştırıp birbirinin içine yedirerek kesintisiz ve yumuşak geçişler üreten pratik ayar.',
    downloadUrl: 'https://parsmazi.com/packs/trans-blur-dissolve.ffx',
    fileSize: '18 KB',
    fileType: '.ffx',
    author: 'Pars Mazi',
    categoryId: 'gecis-efektleri',
    views: 310,
    downloads: 150,
    requirements: ['After Effects Fast Box Blur'],
    parameters: [
      { key: 'Blur Radius Peak', value: '80px' },
      { key: 'Opacity Fade', value: 'Cross' },
    ]
  },
  {
    id: 'trans-zoom-out-bounce',
    name: 'Zoom Out Bounce Transition',
    description: 'Sahneden hızlıca geri çekilip hafif yaylanma (bounce) efektiyle yeni klibe oturan eğlencelik akıcı geçiş.',
    downloadUrl: 'https://parsmazi.com/packs/trans-zoom-out-bounce.ffx',
    fileSize: '26 KB',
    fileType: '.ffx',
    author: 'Pars Mazi',
    categoryId: 'gecis-efektleri',
    views: 420,
    downloads: 215,
    requirements: ['Motion Tile', 'Sapphire Distort'],
    parameters: [
      { key: 'Scale End', value: '100%' },
      { key: 'Scale Start', value: '45%' },
    ]
  },

  // --- DİĞER EFEKTLER (5) ---
  {
    id: 'fx-saber-outline',
    name: 'Neon Saber Edge Outline',
    description: 'Videodaki nesnelerin veya karakterlerin kenarlarını otomatik algılayıp parlayan bir neon çizgisiyle çevreleyen neon efekti.',
    downloadUrl: 'https://parsmazi.com/packs/fx-saber-outline.ffx',
    fileSize: '55 KB',
    fileType: '.ffx',
    author: 'Pars Mazi',
    categoryId: 'diger-efektler',
    views: 610,
    downloads: 320,
    requirements: ['Video Copilot Saber (Free)'],
    parameters: [
      { key: 'Glow Intensity', value: '50%' },
      { key: 'Preset', value: 'Energize' },
      { key: 'Core Type', value: 'Layer Masks' },
    ]
  },
  {
    id: 'fx-rgb-split',
    name: 'Chromatic RGB Split / Aberration',
    description: 'Renk kanallarını (Kırmızı, Yeşil, Mavi) birbirinden ayırarak sinematik bir mercek kusuru ve 3D derinlik algısı oluşturan ffx.',
    downloadUrl: 'https://parsmazi.com/packs/fx-rgb-split.ffx',
    fileSize: '22 KB',
    fileType: '.ffx',
    author: 'Pars Mazi',
    categoryId: 'diger-efektler',
    views: 430,
    downloads: 240,
    requirements: ['Quick Chromatic Attribution (Free) or Sapphire'],
    parameters: [
      { key: 'Red Shift', value: '+3.5px' },
      { key: 'Blue Shift', value: '-3.5px' },
    ]
  },
  {
    id: 'fx-turbulent-water',
    name: 'Turbulent Water Ripple FX',
    description: 'Görüntüye dalgalı bir su yansıması veya sıcaklık dalgalanması efekti veren, arka planlarda hareketlilik yaratan preset.',
    downloadUrl: 'https://parsmazi.com/packs/fx-turbulent-water.ffx',
    fileSize: '17 KB',
    fileType: '.ffx',
    author: 'Pars Mazi',
    categoryId: 'diger-efektler',
    views: 290,
    downloads: 130,
    requirements: ['After Effects Turbulent Displace'],
    parameters: [
      { key: 'Amount', value: '35' },
      { key: 'Size', value: '120' },
      { key: 'Evolution Rate', value: '2.5 / s' },
    ]
  },
  {
    id: 'fx-halftone-dots',
    name: 'Comic Book Halftone Dots',
    description: 'Görüntüyü çizgi roman tarzı noktalı (Halftone) bir dokuya büründüren, sanatsal ve manga tarzı kurgular için eşsiz bir filtre.',
    downloadUrl: 'https://parsmazi.com/packs/fx-halftone-dots.ffx',
    fileSize: '34 KB',
    fileType: '.ffx',
    author: 'Pars Mazi',
    categoryId: 'diger-efektler',
    views: 312,
    downloads: 160,
    requirements: ['BCC Halftone or Sapphire Toy'],
    parameters: [
      { key: 'Dot Size', value: '4.0' },
      { key: 'Pattern Angle', value: '45°' },
    ]
  },
  {
    id: 'fx-glow-aura',
    name: 'Vaporwave Edge Glow Aura',
    description: 'Videodaki parlak alanlardan dışarı doğru taşan, yumuşak renk geçişli estetik bir aura parıltısı üreten glow preseti.',
    downloadUrl: 'https://parsmazi.com/packs/fx-glow-aura.ffx',
    fileSize: '29 KB',
    fileType: '.ffx',
    author: 'Pars Mazi',
    categoryId: 'diger-efektler',
    views: 380,
    downloads: 195,
    requirements: ['Deep Glow', 'S_Glow'],
    parameters: [
      { key: 'Aura Tint', value: 'Pink/Cyan' },
      { key: 'Glow Radius', value: '250' },
    ]
  },

  // --- SES EFEKTLERİ (24) ---
  // We will build synthesized browser audio for these when played!
  {
    id: 'sfx-whoosh-fast',
    name: 'Whoosh Transition (Hızlı Geçiş)',
    description: 'Hızlı geçişler, kamera kaymaları ve ani hareketler için rüzgar uğultusu sesi.',
    downloadUrl: 'https://parsmazi.com/sfx/whoosh-fast.wav',
    fileSize: '142 KB',
    fileType: '.wav',
    author: 'Pars Mazi',
    categoryId: 'ses-efektleri',
    views: 950,
    downloads: 620,
  },
  {
    id: 'sfx-bass-drop',
    name: 'Cinematic Bass Drop (Derin Bas)',
    description: 'Vuruş anlarında, büyük patlamalarda veya sahne girişlerinde sarsıcı, derin sinematik bas darbesi.',
    downloadUrl: 'https://parsmazi.com/sfx/bass-drop.wav',
    fileSize: '320 KB',
    fileType: '.wav',
    author: 'Pars Mazi',
    categoryId: 'ses-efektleri',
    views: 890,
    downloads: 580,
  },
  {
    id: 'sfx-glitch-crack',
    name: 'Digital Glitch Crackle (Dijital Hata)',
    description: 'Glitch efektleri ve ekran bozulmaları için yüksek frekanslı dijital çatırdama ve bozulma sesi.',
    downloadUrl: 'https://parsmazi.com/sfx/glitch-crack.wav',
    fileSize: '95 KB',
    fileType: '.wav',
    author: 'Pars Mazi',
    categoryId: 'ses-efektleri',
    views: 620,
    downloads: 390,
  },
  {
    id: 'sfx-camera-shutter',
    name: 'Camera Shutter Click (Deklanşör)',
    description: 'Fotoğraf çekimi, anlık donma ve flaş patlama anları için mekanik kamera deklanşör sesi.',
    downloadUrl: 'https://parsmazi.com/sfx/camera-shutter.wav',
    fileSize: '68 KB',
    fileType: '.wav',
    author: 'Pars Mazi',
    categoryId: 'ses-efektleri',
    views: 740,
    downloads: 480,
  },
  {
    id: 'sfx-vinyl-scratch',
    name: 'Vinyl Record Scratch (Plak Çiziği)',
    description: 'Müziğin aniden durduğu, komik veya şaşırtıcı sahnelerde kullanılan retro plak durma sesi.',
    downloadUrl: 'https://parsmazi.com/sfx/vinyl-scratch.wav',
    fileSize: '180 KB',
    fileType: '.wav',
    author: 'Pars Mazi',
    categoryId: 'ses-efektleri',
    views: 510,
    downloads: 290,
  },
  {
    id: 'sfx-sword-slash',
    name: 'Sword Slash Swoosh (Kılıç Kesmesi)',
    description: 'Aksiyon, dövüş ve kılıç sallama sahneleri için keskin, metalik rüzgar kesme sesi.',
    downloadUrl: 'https://parsmazi.com/sfx/sword-slash.wav',
    fileSize: '110 KB',
    fileType: '.wav',
    author: 'Pars Mazi',
    categoryId: 'ses-efektleri',
    views: 430,
    downloads: 240,
  },
  {
    id: 'sfx-riser-build',
    name: 'Tension Riser Build-Up (Yükseltici)',
    description: 'Sahnede gerilimi tırmandıran, patlama öncesi sürekli yükselen tiz sinematik ses efekti.',
    downloadUrl: 'https://parsmazi.com/sfx/riser-build.wav',
    fileSize: '450 KB',
    fileType: '.wav',
    author: 'Pars Mazi',
    categoryId: 'ses-efektleri',
    views: 590,
    downloads: 380,
  },
  {
    id: 'sfx-impact-sub',
    name: 'Deep Sub Impact (Derin Darbe)',
    description: 'Ağır cisim çarpması, tok bas içeren derin ve temiz darbe vuruş efekti.',
    downloadUrl: 'https://parsmazi.com/sfx/impact-sub.wav',
    fileSize: '240 KB',
    fileType: '.wav',
    author: 'Pars Mazi',
    categoryId: 'ses-efektleri',
    views: 480,
    downloads: 295,
  },
  {
    id: 'sfx-glass-shatter',
    name: 'Glass Shatter Break (Cam Kırılması)',
    description: 'Pencerelerin patlaması, bardak kırılması veya kristal darbe anları için gerçekçi cam tuzla buz olma sesi.',
    downloadUrl: 'https://parsmazi.com/sfx/glass-shatter.wav',
    fileSize: '210 KB',
    fileType: '.wav',
    author: 'Pars Mazi',
    categoryId: 'ses-efektleri',
    views: 390,
    downloads: 180,
  },
  {
    id: 'sfx-bell-ring',
    name: 'Retro Telephone Bell Ring (Zil Sesi)',
    description: 'Eski tip telefonların klasik mekanik çınlama sesi, retro sahneler için.',
    downloadUrl: 'https://parsmazi.com/sfx/bell-ring.wav',
    fileSize: '150 KB',
    fileType: '.wav',
    author: 'Pars Mazi',
    categoryId: 'ses-efektleri',
    views: 280,
    downloads: 120,
  },
  {
    id: 'sfx-laser-pew',
    name: 'Retro Laser Pew (Ateri Lazeri)',
    description: '80\'ler arcade oyunlarındaki fütüristik bilim kurgu lazer atış sesi.',
    downloadUrl: 'https://parsmazi.com/sfx/laser-pew.wav',
    fileSize: '85 KB',
    fileType: '.wav',
    author: 'Pars Mazi',
    categoryId: 'ses-efektleri',
    views: 340,
    downloads: 155,
  },
  {
    id: 'sfx-clock-tick',
    name: 'Ticking Wall Clock (Saat Tıkırtısı)',
    description: 'Süre kısıtlaması olan gerilim veya bekleyiş sahneleri için ritmik analog duvar saati tıkırtısı.',
    downloadUrl: 'https://parsmazi.com/sfx/clock-tick.wav',
    fileSize: '120 KB',
    fileType: '.wav',
    author: 'Pars Mazi',
    categoryId: 'ses-efektleri',
    views: 410,
    downloads: 230,
  },
  {
    id: 'sfx-keyboard-type',
    name: 'Mechanical Keyboard Typing (Klavye)',
    description: 'Hızlı mekanik klavye tuş sesleri, dijital yazım ve kod yazma efektleri için.',
    downloadUrl: 'https://parsmazi.com/sfx/keyboard-type.wav',
    fileSize: '190 KB',
    fileType: '.wav',
    author: 'Pars Mazi',
    categoryId: 'ses-efektleri',
    views: 520,
    downloads: 310,
  },
  {
    id: 'sfx-gunshot-echo',
    name: 'Desert Eagle Gunshot with Echo (Silah)',
    description: 'Geniş bir alanda yankılanan, patlayıcı ve güçlü tabanca ateşleme sesi.',
    downloadUrl: 'https://parsmazi.com/sfx/gunshot-echo.wav',
    fileSize: '290 KB',
    fileType: '.wav',
    author: 'Pars Mazi',
    categoryId: 'ses-efektleri',
    views: 640,
    downloads: 380,
  },
  {
    id: 'sfx-heartbeat-slow',
    name: 'Deep Human Heartbeat (Kalp Atışı)',
    description: 'Korku, heyecan veya hayati tehlike anlarında duyulan derin ritmik kalp atış ritmi.',
    downloadUrl: 'https://parsmazi.com/sfx/heartbeat-slow.wav',
    fileSize: '160 KB',
    fileType: '.wav',
    author: 'Pars Mazi',
    categoryId: 'ses-efektleri',
    views: 430,
    downloads: 210,
  },
  {
    id: 'sfx-bubble-pop',
    name: 'Water Bubble Pop (Baloncuk Sesi)',
    description: 'Şirin animasyonlar, su altı efektleri veya hafif bildirimler için tatlı baloncuk patlama sesi.',
    downloadUrl: 'https://parsmazi.com/sfx/bubble-pop.wav',
    fileSize: '45 KB',
    fileType: '.wav',
    author: 'Pars Mazi',
    categoryId: 'ses-efektleri',
    views: 310,
    downloads: 140,
  },
  {
    id: 'sfx-metal-clang',
    name: 'Heavy Industrial Metal Clang (Demir Sesi)',
    description: 'Fabrika sahneleri, kılıç çarpışmaları veya ağır demir kapı kapanışları için metalik tok ses.',
    downloadUrl: 'https://parsmazi.com/sfx/metal-clang.wav',
    fileSize: '220 KB',
    fileType: '.wav',
    author: 'Pars Mazi',
    categoryId: 'ses-efektleri',
    views: 350,
    downloads: 165,
  },
  {
    id: 'sfx-paper-rustle',
    name: 'Paper Sheet Rustle (Kağıt Hışırtısı)',
    description: 'Kitap saygası çevirme, harita açma veya kağıt buruşturma sahneleri için doğal hışırtı.',
    downloadUrl: 'https://parsmazi.com/sfx/paper-rustle.wav',
    fileSize: '95 KB',
    fileType: '.wav',
    author: 'Pars Mazi',
    categoryId: 'ses-efektleri',
    views: 290,
    downloads: 110,
  },
  {
    id: 'sfx-rain-loop',
    name: 'Cozy Rain on Window (Yağmur Sesi)',
    description: 'Lo-fi kurgular veya hüzünlü anlar için pencereye vuran hafif dinlendirici yağmur fısıltısı.',
    downloadUrl: 'https://parsmazi.com/sfx/rain-loop.wav',
    fileSize: '620 KB',
    fileType: '.wav',
    author: 'Pars Mazi',
    categoryId: 'ses-efektleri',
    views: 580,
    downloads: 340,
  },
  {
    id: 'sfx-thunder-strike',
    name: 'Distant Thunder Strike (Gök Gürlemesi)',
    description: 'Yağmurlu ve karanlık geceleri betimlemek için derin ve sarsıcı uzaktan gelen gök gürültüsü patlaması.',
    downloadUrl: 'https://parsmazi.com/sfx/thunder-strike.wav',
    fileSize: '380 KB',
    fileType: '.wav',
    author: 'Pars Mazi',
    categoryId: 'ses-efektleri',
    views: 490,
    downloads: 230,
  },
  {
    id: 'sfx-cyber-beep',
    name: 'Sci-Fi Hologram Interface Beep (Bip)',
    description: 'Bilgisayar arayüzleri, hedef kilitlenmeleri veya teknolojik bildirimler için ince elektronik ses.',
    downloadUrl: 'https://parsmazi.com/sfx/cyber-beep.wav',
    fileSize: '55 KB',
    fileType: '.wav',
    author: 'Pars Mazi',
    categoryId: 'ses-efektleri',
    views: 340,
    downloads: 190,
  },
  {
    id: 'sfx-laughter-crowd',
    name: 'Sitcom TV Laughter Crowd (Gülüş Sesi)',
    description: 'Eski sitcom dizilerindeki gibi arka planda yükselen toplu televizyon stüdyosu kahkahası.',
    downloadUrl: 'https://parsmazi.com/sfx/laughter-crowd.wav',
    fileSize: '410 KB',
    fileType: '.wav',
    author: 'Pars Mazi',
    categoryId: 'ses-efektleri',
    views: 270,
    downloads: 95,
  },
  {
    id: 'sfx-ufo-hum',
    name: 'Mysterious Alien UFO Hover Hum (Uğultu)',
    description: 'Uzay gemisi yakınlaşması veya gizemli bilim kurgu manyetik alan salınımı yapan bas uğultusu.',
    downloadUrl: 'https://parsmazi.com/sfx/ufo-hum.wav',
    fileSize: '490 KB',
    fileType: '.wav',
    author: 'Pars Mazi',
    categoryId: 'ses-efektleri',
    views: 310,
    downloads: 130,
  },
  {
    id: 'sfx-static-white',
    name: 'Analog TV Static White Noise (Karıncalanma)',
    description: 'Sinyali kesilen tüplü televizyonların ve VHS kasetlerin karlı ekran hışırtısı sesi.',
    downloadUrl: 'https://parsmazi.com/sfx/static-white.wav',
    fileSize: '330 KB',
    fileType: '.wav',
    author: 'Pars Mazi',
    categoryId: 'ses-efektleri',
    views: 420,
    downloads: 185,
  },
];

export const PORTFOLIO_VIDEOS = [
  {
    id: 'port-1',
    title: 'Valorant Edit Pack Showcase (3D Motion Graphics)',
    category: 'Motion Design',
    views: '45K+',
    duration: '1:45',
    thumbnail: 'https://picsum.photos/seed/valorant/600/400',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
  },
  {
    id: 'port-2',
    title: 'Anime Music Video (AMV) - Neon Vibe Edit',
    category: 'VFX / Color Grading',
    views: '120K+',
    duration: '2:15',
    thumbnail: 'https://picsum.photos/seed/anime/600/400',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
  },
  {
    id: 'port-3',
    title: 'Cinematic Travel Vlog - Turkey After Effects VFX',
    category: 'Video Editing',
    views: '35K+',
    duration: '3:40',
    thumbnail: 'https://picsum.photos/seed/travel/600/400',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
  },
  {
    id: 'port-4',
    title: '3D Typography & Logo Animation Reel',
    category: '3D Motion',
    views: '28K+',
    duration: '1:00',
    thumbnail: 'https://picsum.photos/seed/typography/600/400',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
  }
];
